# Generated by Django 5.2.8 on 2025-12-01 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyAnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("total_projects", models.IntegerField(default=0)),
                ("active_projects", models.IntegerField(default=0)),
                ("completed_projects", models.IntegerField(default=0)),
                ("total_tickets", models.IntegerField(default=0)),
                ("open_tickets", models.IntegerField(default=0)),
                ("in_progress_tickets", models.IntegerField(default=0)),
                ("closed_tickets", models.IntegerField(default=0)),
                ("total_invoices", models.IntegerField(default=0)),
                ("paid_invoices", models.IntegerField(default=0)),
                ("unpaid_invoices", models.IntegerField(default=0)),
                ("revenue", models.FloatField(default=0)),
                ("outstanding_balance", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_analytics",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-date",),
                "unique_together": {("organization", "date")},
            },
        ),
        migrations.CreateModel(
            name="FinancialAnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("total_invoices", models.IntegerField(default=0)),
                ("paid_invoices", models.IntegerField(default=0)),
                ("unpaid_invoices", models.IntegerField(default=0)),
                ("total_revenue", models.FloatField(default=0)),
                ("outstanding_balance", models.FloatField(default=0)),
                ("paid_today", models.FloatField(default=0)),
                ("unpaid_today", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_financials",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-date",),
                "unique_together": {("organization", "date")},
            },
        ),
        migrations.CreateModel(
            name="TechnicianProductivitySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("tickets_assigned", models.IntegerField(default=0)),
                ("tickets_closed", models.IntegerField(default=0)),
                ("avg_resolution_hours", models.FloatField(default=0)),
                ("projects_assigned", models.IntegerField(default=0)),
                ("projects_completed", models.IntegerField(default=0)),
                ("productivity_score", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technician_productivity",
                        to="organizations.organization",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productivity_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date",),
                "unique_together": {("technician", "date")},
            },
        ),
    ]
